// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: logAndApply.proto

#include "logAndApply.pb.h"
#include "logAndApply.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace logapply {

static const char* logAndApply_method_names[] = {
  "/logapply.logAndApply/logAndApply",
};

std::unique_ptr< logAndApply::Stub> logAndApply::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< logAndApply::Stub> stub(new logAndApply::Stub(channel));
  return stub;
}

logAndApply::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_logAndApply_(logAndApply_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status logAndApply::Stub::logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::logapply::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::logapply::EditLists, ::logapply::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_logAndApply_, context, request, response);
}

void logAndApply::Stub::experimental_async::logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists* request, ::logapply::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::logapply::EditLists, ::logapply::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_logAndApply_, context, request, response, std::move(f));
}

void logAndApply::Stub::experimental_async::logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists* request, ::logapply::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_logAndApply_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::logapply::Response>* logAndApply::Stub::PrepareAsynclogAndApplyRaw(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::logapply::Response, ::logapply::EditLists, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_logAndApply_, context, request);
}

::grpc::ClientAsyncResponseReader< ::logapply::Response>* logAndApply::Stub::AsynclogAndApplyRaw(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynclogAndApplyRaw(context, request, cq);
  result->StartCall();
  return result;
}

logAndApply::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      logAndApply_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< logAndApply::Service, ::logapply::EditLists, ::logapply::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](logAndApply::Service* service,
             ::grpc::ServerContext* ctx,
             const ::logapply::EditLists* req,
             ::logapply::Response* resp) {
               return service->logAndApply(ctx, req, resp);
             }, this)));
}

logAndApply::Service::~Service() {
}

::grpc::Status logAndApply::Service::logAndApply(::grpc::ServerContext* context, const ::logapply::EditLists* request, ::logapply::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace logapply

