// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: logAndApply.proto
#ifndef GRPC_logAndApply_2eproto__INCLUDED
#define GRPC_logAndApply_2eproto__INCLUDED

#include "logAndApply.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace logapply {

// The logAndApply service.
class logAndApply final {
 public:
  static constexpr char const* service_full_name() {
    return "logapply.logAndApply";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::logapply::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logapply::Response>> AsynclogAndApply(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logapply::Response>>(AsynclogAndApplyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logapply::Response>> PrepareAsynclogAndApply(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logapply::Response>>(PrepareAsynclogAndApplyRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists* request, ::logapply::Response* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists* request, ::logapply::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists* request, ::logapply::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logapply::Response>* AsynclogAndApplyRaw(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logapply::Response>* PrepareAsynclogAndApplyRaw(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::logapply::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logapply::Response>> AsynclogAndApply(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logapply::Response>>(AsynclogAndApplyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logapply::Response>> PrepareAsynclogAndApply(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logapply::Response>>(PrepareAsynclogAndApplyRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists* request, ::logapply::Response* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists* request, ::logapply::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void logAndApply(::grpc::ClientContext* context, const ::logapply::EditLists* request, ::logapply::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::logapply::Response>* AsynclogAndApplyRaw(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::logapply::Response>* PrepareAsynclogAndApplyRaw(::grpc::ClientContext* context, const ::logapply::EditLists& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_logAndApply_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status logAndApply(::grpc::ServerContext* context, const ::logapply::EditLists* request, ::logapply::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_logAndApply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_logAndApply() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_logAndApply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status logAndApply(::grpc::ServerContext* /*context*/, const ::logapply::EditLists* /*request*/, ::logapply::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestlogAndApply(::grpc::ServerContext* context, ::logapply::EditLists* request, ::grpc::ServerAsyncResponseWriter< ::logapply::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_logAndApply<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_logAndApply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_logAndApply() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::logapply::EditLists, ::logapply::Response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::logapply::EditLists* request, ::logapply::Response* response) { return this->logAndApply(context, request, response); }));}
    void SetMessageAllocatorFor_logAndApply(
        ::grpc::experimental::MessageAllocator< ::logapply::EditLists, ::logapply::Response>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::logapply::EditLists, ::logapply::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_logAndApply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status logAndApply(::grpc::ServerContext* /*context*/, const ::logapply::EditLists* /*request*/, ::logapply::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* logAndApply(
      ::grpc::CallbackServerContext* /*context*/, const ::logapply::EditLists* /*request*/, ::logapply::Response* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* logAndApply(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::logapply::EditLists* /*request*/, ::logapply::Response* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_logAndApply<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_logAndApply<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_logAndApply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_logAndApply() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_logAndApply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status logAndApply(::grpc::ServerContext* /*context*/, const ::logapply::EditLists* /*request*/, ::logapply::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_logAndApply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_logAndApply() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_logAndApply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status logAndApply(::grpc::ServerContext* /*context*/, const ::logapply::EditLists* /*request*/, ::logapply::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestlogAndApply(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_logAndApply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_logAndApply() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->logAndApply(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_logAndApply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status logAndApply(::grpc::ServerContext* /*context*/, const ::logapply::EditLists* /*request*/, ::logapply::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* logAndApply(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* logAndApply(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_logAndApply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_logAndApply() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::logapply::EditLists, ::logapply::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::logapply::EditLists, ::logapply::Response>* streamer) {
                       return this->StreamedlogAndApply(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_logAndApply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status logAndApply(::grpc::ServerContext* /*context*/, const ::logapply::EditLists* /*request*/, ::logapply::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedlogAndApply(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::logapply::EditLists,::logapply::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_logAndApply<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_logAndApply<Service > StreamedService;
};

}  // namespace logapply


#endif  // GRPC_logAndApply_2eproto__INCLUDED
